name: DeviceMinder CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: setup postgres
      uses: ikalnytskyi/action-setup-postgres@v5
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    - name: Install Dependecies
      run: |
        poetry install
    - name: Run Tests
      run: |
        sudo systemctl start postgresql.service
        cd src
        poetry run python tests.py
      env:
        ALGORITHM: ${{ secrets.ALGORITHM }}
        SERVICE_HOST: ${{ secrets.SERVICE_HOST }}
        SERVICE_PORT: ${{ secrets.SERVICE_PORT }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
        STRIPE_WEBHOOK_KEY: ${{ secrets.STRIPE_WEBHOOK_KEY }}
        SQLALCHEMY_DATABASE_URL: ${{ secrets.SQLALCHEMY_DATABASE_URL }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_DB: dm-payments
        POSTGRES_PASSWORD: 48bc27agh!
        POSTGRES_USER: postgres
